name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          distribution: "oracle"
          java-version: "24"

      - name: Run tests
        working-directory: ./task2
        run: java --enable-preview build.java test

      - name: Publish coverage report
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.1
        with:
          paths: |
            ${{ github.workspace }}/**/target/coverage-report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 85
          min-coverage-changed-files: 85
